#include "GL_Program.h"

#include "MG_State/GLState/Core.h"

namespace MobileGL {
    namespace MG_Impl::GLImpl {
        static bool CheckShaderNameValidity(Uint shader) {
            if (!MG_State::pGLContext->ValidateShaderName(shader)) {
                MG_State::pGLContext->RecordError(
                    ErrorCode::InvalidValue,
                    MakeShared<GenericErrorInfo>("MG_Impl/GLImpl", __func__,
                                                 "`shader` is not a value generated by OpenGL."));
                return false;
            }
            return true;
        }

        static SharedPtr<MG_State::GLState::ShaderObject> TryToGetShaderObject(Uint shader) {
            if (!CheckShaderNameValidity(shader))
                return nullptr;

            auto shaderObject = MG_State::pGLContext->GetShaderObject(shader);
            if (!shaderObject) {
                MG_State::pGLContext->RecordError(
                    ErrorCode::InvalidOperation,
                    MakeShared<GenericErrorInfo>("MG_Impl/GLImpl", __func__,
                                                 "`shader` is not a shader object."));
                return nullptr;
            }
            return shaderObject;
        }

        static bool CheckProgramNameValidity(GLuint program) {
            if (!MG_State::pGLContext->ValidateProgramName(program)) {
                MG_State::pGLContext->RecordError(
                    ErrorCode::InvalidValue,
                    MakeShared<GenericErrorInfo>("MG_Impl/GLImpl", __func__,
                                                 "`program` is not a value generated by OpenGL"));
                return false;
            }
            return true;
        }

        static SharedPtr<MG_State::GLState::ProgramObject> TryToGetProgramObject(GLuint program) {
            if (!CheckProgramNameValidity(program))
                return nullptr;

            auto programObject = MG_State::pGLContext->GetProgramObject(program);
            if (!programObject) {
                MG_State::pGLContext->RecordError(
                    ErrorCode::InvalidOperation,
                    MakeShared<GenericErrorInfo>("MG_Impl/GLImpl", __func__,
                                                 "`program` is not a program object."));
                return nullptr;
            }
            return programObject;
        }

        void CopyStr(GLsizei bufSize, GLsizei *length, GLchar *dst, const char* src, GLsizei srcLength) {
            auto sz = std::min(bufSize - 1, srcLength);
            if (length)
                *length = sz;
            memcpy(dst, src, sz);
            dst[sz] = '\0';
        }

        void AttachShader_State(GLuint program, GLuint shader) {
            auto programObject = TryToGetProgramObject(program);
            if (!programObject)
                return;
            auto shaderObject = TryToGetShaderObject(shader);
            if (!shaderObject)
                return;
            if (!programObject->AttachShader(shaderObject)) {
                MG_State::pGLContext->RecordError(
                    ErrorCode::InvalidOperation,
                    MakeShared<GenericErrorInfo>("MG_Impl/GLImpl", __func__,
                                                 "`shader` is already attached to `program`."));
                return;
            }
        }

        void BindAttribLocation_State(GLuint program, GLuint index, const GLchar* name) {
            THROW_UNIMPL_EXCEPTION;
        }

        void CompileShader_State(GLuint shader) {
            auto shaderObject = TryToGetShaderObject(shader);
            if (!shaderObject)
                return;
            shaderObject->Compile();
        }

        GLuint CreateProgram_State(void) {
            return MG_State::pGLContext->CreateProgram();
        }

        GLuint CreateShader_State(GLenum type) {
            auto shaderId = MG_State::pGLContext->CreateShader(MG_State::GLState::GetMGLShaderStageByGLShaderType(type));
            if (shaderId == 0) {
                MG_State::pGLContext->RecordError(
                    ErrorCode::InvalidValue,
                    MakeShared<GenericErrorInfo>("MG_Impl/GLImpl", __func__,
                        "`shaderType` is not an accepted value."));
                return 0;
            }
            return shaderId;
        }

        void DeleteProgram_State(GLuint program) {
            if (!CheckProgramNameValidity(program))
                return;
            MG_State::pGLContext->MarkProgramForDeletion(program);
        }

        void DeleteShader_State(GLuint shader) {
            if (!CheckProgramNameValidity(shader))
                return;
            MG_State::pGLContext->MarkShaderForDeletion(shader);
        }

        void DetachShader_State(GLuint program, GLuint shader) {
            auto shaderObject = TryToGetShaderObject(shader);
            if (!shaderObject)
                return;
            auto programObject = TryToGetProgramObject(program);
            if (!programObject)
                return;

            auto count = programObject->DetachShader(shaderObject);
            if (count <= 0) {
                MG_State::pGLContext->RecordError(
                    ErrorCode::InvalidOperation,
                    MakeShared<GenericErrorInfo>("MG_Impl/GLImpl", __func__,
                                                 "Shader is not attached to program."));
                return;
            }
        }

        void GetActiveAttrib_State(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size,
                                   GLenum* type, GLchar* name) {
            THROW_UNIMPL_EXCEPTION;
        }

        void GetActiveUniform_State(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size,
                                    GLenum* type, GLchar* name) {
            THROW_UNIMPL_EXCEPTION;
        }

        void GetAttachedShaders_State(GLuint program, GLsizei maxCount, GLsizei* count, GLuint* shaders) {
            if (maxCount < 0) {
                MG_State::pGLContext->RecordError(
                        ErrorCode::InvalidValue,
                        MakeShared<GenericErrorInfo>("MG_Impl/GLImpl", __func__,
                                                     "`maxCount` is less than 0."));
                return;
            }
            auto programObject = TryToGetProgramObject(program);
            if (!programObject)
                return;
            const auto& s = programObject->GetAttachedShaders();
            GLsizei c = std::min((GLsizei)s.size(), maxCount);
            if (count)
                *count = c;
            for (GLsizei i = 0; i < c; ++i) {
                shaders[i] = s[i]->GetId();
            }
        }

        GLint GetAttribLocation_State(GLuint program, const GLchar* name) {
            THROW_UNIMPL_EXCEPTION;
        }

        void GetProgramiv_State(GLuint program, GLenum pname, GLint* params) {
            THROW_UNIMPL_EXCEPTION;
        }

        void GetProgramInfoLog_State(GLuint program, GLsizei bufSize, GLsizei* length, GLchar* infoLog) {
            auto programObject = TryToGetProgramObject(program);
            if (!programObject)
                return;

            const auto& log = programObject->GetInfoLog();
            CopyStr(bufSize, length, infoLog, log.c_str(), log.length());
        }

        void GetShaderiv_State(GLuint shader, GLenum pname, GLint* params) {
            THROW_UNIMPL_EXCEPTION;
        }

        void GetShaderInfoLog_State(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* infoLog) {
            auto shaderObject = TryToGetShaderObject(shader);
            if (!shaderObject)
                return;

            const auto& log = shaderObject->GetInfoLog();
            CopyStr(bufSize, length, infoLog, log.c_str(), log.length());
        }

        void GetShaderSource_State(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* source) {
            if (bufSize < 0) {
                MG_State::pGLContext->RecordError(
                        ErrorCode::InvalidValue,
                        MakeShared<GenericErrorInfo>("MG_Impl/GLImpl", __func__,
                                                     "`bufSize` is less than 0."));
            }

            auto shaderObject = TryToGetShaderObject(shader);
            if (!shaderObject)
                return;

            auto& src = shaderObject->GetShaderSource();
            CopyStr(bufSize, length, source, src.c_str(), src.length());
        }



        GLint GetUniformLocation_State(GLuint program, const GLchar* name) {
            THROW_UNIMPL_EXCEPTION;
        }

        void GetUniformfv_State(GLuint program, GLint location, GLfloat* params) {
            THROW_UNIMPL_EXCEPTION;
        }

        void GetUniformiv_State(GLuint program, GLint location, GLint* params) {
            THROW_UNIMPL_EXCEPTION;
        }

        GLboolean IsProgram_State(GLuint program) {
            /* FIXME: Handle situations that:
             * A program object marked for deletion with glDeleteProgram but still in use as part of current
             * rendering state is still considered a program object and glIsProgram will return GL_TRUE.
            */
            return CheckProgramNameValidity(program);
        }

        GLboolean IsShader_State(GLuint shader) {
            /* FIXME: Handle situations that:
             * A shader object marked for deletion with glDeleteShader but still attached to a program object is still
             * considered a shader object and glIsShader will return GL_TRUE.
            */
            return CheckShaderNameValidity(shader);
        }

        void LinkProgram_State(GLuint program) {
            auto programObject = TryToGetProgramObject(program);
            if (!programObject)
                return;
            programObject->Link();
        }

        void ShaderSource_State(GLuint shader, GLsizei count, const GLchar* const* string, const GLint* length) {
            if (count < 0) {
                MG_State::pGLContext->RecordError(
                    ErrorCode::InvalidValue,
                    MakeShared<GenericErrorInfo>("MG_Impl/GLImpl", __func__,
                                             "`count` is less than 0."));
            }

            auto shaderObject = TryToGetShaderObject(shader);
            if (!shaderObject)
                return;

            std::string src;
            for (GLsizei i = 0; i < count; i++) {
                src +=
                    (length == nullptr || length[i] <= 0) ? string[i] : std::string(string[i], length[i]);
            }
            shaderObject->SetShaderSource(Move(src));
        }

        void UseProgram_State(GLuint program) {
            if (program == 0) {
                MG_State::pGLContext->UseProgram(0);
                return;
            }

            auto programObject = TryToGetProgramObject(program);
            if (!programObject)
                return;
            MG_State::pGLContext->UseProgram(program);

        }

        void Uniform1f_State(GLint location, GLfloat v0) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform2f_State(GLint location, GLfloat v0, GLfloat v1) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform3f_State(GLint location, GLfloat v0, GLfloat v1, GLfloat v2) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform4f_State(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform1i_State(GLint location, GLint v0) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform2i_State(GLint location, GLint v0, GLint v1) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform3i_State(GLint location, GLint v0, GLint v1, GLint v2) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform4i_State(GLint location, GLint v0, GLint v1, GLint v2, GLint v3) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform1fv_State(GLint location, GLsizei count, const GLfloat* value) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform2fv_State(GLint location, GLsizei count, const GLfloat* value) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform3fv_State(GLint location, GLsizei count, const GLfloat* value) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform4fv_State(GLint location, GLsizei count, const GLfloat* value) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform1iv_State(GLint location, GLsizei count, const GLint* value) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform2iv_State(GLint location, GLsizei count, const GLint* value) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform3iv_State(GLint location, GLsizei count, const GLint* value) {
            THROW_UNIMPL_EXCEPTION;
        }

        void Uniform4iv_State(GLint location, GLsizei count, const GLint* value) {
            THROW_UNIMPL_EXCEPTION;
        }

        void UniformMatrix2fv_State(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
            THROW_UNIMPL_EXCEPTION;
        }

        void UniformMatrix3fv_State(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
            THROW_UNIMPL_EXCEPTION;
        }

        void UniformMatrix4fv_State(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
            THROW_UNIMPL_EXCEPTION;
        }

        void ValidateProgram_State(GLuint program) {
            THROW_UNIMPL_EXCEPTION;
        }

        void AttachShader(GLuint program, GLuint shader) {
            AttachShader_State(program, shader);
        }

        void BindAttribLocation(GLuint program, GLuint index, const GLchar* name) {
            BindAttribLocation_State(program, index, name);
        }

        void CompileShader(GLuint shader) {
            CompileShader_State(shader);
        }
        GLuint CreateProgram(void) {
            return CreateProgram_State();
        }

        GLuint CreateShader(GLenum type) {
            return CreateShader_State(type);
        }

        void DeleteProgram(GLuint program) {
            DeleteProgram_State(program);
        }

        void DeleteShader(GLuint shader) {
            DeleteShader_State(shader);
        }

        void DetachShader(GLuint program, GLuint shader) {
            DetachShader_State(program, shader);
        }

        void GetActiveAttrib(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type,
                             GLchar* name) {
            GetActiveAttrib_State(program, index, bufSize, length, size, type, name);
        }

        void GetActiveUniform(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type,
                              GLchar* name) {
            GetActiveUniform_State(program, index, bufSize, length, size, type, name);
        }

        void GetAttachedShaders(GLuint program, GLsizei maxCount, GLsizei* count, GLuint* shaders) {
            GetAttachedShaders_State(program, maxCount, count, shaders);
        }

        GLint GetAttribLocation(GLuint program, const GLchar* name) {
            return GetAttribLocation_State(program, name);
        }

        void GetProgramiv(GLuint program, GLenum pname, GLint* params) {
            GetProgramiv_State(program, pname, params);
        }

        void GetProgramInfoLog(GLuint program, GLsizei bufSize, GLsizei* length, GLchar* infoLog) {
            GetProgramInfoLog_State(program, bufSize, length, infoLog);
        }

        void GetShaderiv(GLuint shader, GLenum pname, GLint* params) {
            GetShaderiv_State(shader, pname, params);
        }

        void GetShaderInfoLog(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* infoLog) {
            GetShaderInfoLog_State(shader, bufSize, length, infoLog);
        }

        void GetShaderSource(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* source) {
            GetShaderSource_State(shader, bufSize, length, source);
        }

        GLint GetUniformLocation(GLuint program, const GLchar* name) {
            return GetUniformLocation_State(program, name);
        }

        void GetUniformfv(GLuint program, GLint location, GLfloat* params) {
            GetUniformfv_State(program, location, params);
        }

        void GetUniformiv(GLuint program, GLint location, GLint* params) {
            GetUniformiv_State(program, location, params);
        }
        GLboolean IsProgram(GLuint program) {
            return IsProgram_State(program);
        }
        GLboolean IsShader(GLuint shader) {
            return IsShader_State(shader);
        }

        void LinkProgram(GLuint program) {
            LinkProgram_State(program);
        }

        void ShaderSource(GLuint shader, GLsizei count, const GLchar* const* string, const GLint* length) {
            ShaderSource_State(shader, count, string, length);
        }

        void UseProgram(GLuint program) {
            UseProgram_State(program);
        }

        void Uniform1f(GLint location, GLfloat v0) {
            Uniform1f_State(location, v0);
        }

        void Uniform2f(GLint location, GLfloat v0, GLfloat v1) {
            Uniform2f_State(location, v0, v1);
        }

        void Uniform3f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2) {
            Uniform3f_State(location, v0, v1, v2);
        }

        void Uniform4f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) {
            Uniform4f_State(location, v0, v1, v2, v3);
        }

        void Uniform1i(GLint location, GLint v0) {
            Uniform1i_State(location, v0);
        }

        void Uniform2i(GLint location, GLint v0, GLint v1) {
            Uniform2i_State(location, v0, v1);
        }

        void Uniform3i(GLint location, GLint v0, GLint v1, GLint v2) {
            Uniform3i_State(location, v0, v1, v2);
        }

        void Uniform4i(GLint location, GLint v0, GLint v1, GLint v2, GLint v3) {
            Uniform4i_State(location, v0, v1, v2, v3);
        }

        void Uniform1fv(GLint location, GLsizei count, const GLfloat* value) {
            Uniform1fv_State(location, count, value);
        }

        void Uniform2fv(GLint location, GLsizei count, const GLfloat* value) {
            Uniform2fv_State(location, count, value);
        }

        void Uniform3fv(GLint location, GLsizei count, const GLfloat* value) {
            Uniform3fv_State(location, count, value);
        }

        void Uniform4fv(GLint location, GLsizei count, const GLfloat* value) {
            Uniform4fv_State(location, count, value);
        }

        void Uniform1iv(GLint location, GLsizei count, const GLint* value) {
            Uniform1iv_State(location, count, value);
        }

        void Uniform2iv(GLint location, GLsizei count, const GLint* value) {
            Uniform2iv_State(location, count, value);
        }

        void Uniform3iv(GLint location, GLsizei count, const GLint* value) {
            Uniform3iv_State(location, count, value);
        }

        void Uniform4iv(GLint location, GLsizei count, const GLint* value) {
            Uniform4iv_State(location, count, value);
        }

        void UniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
            UniformMatrix2fv_State(location, count, transpose, value);
        }

        void UniformMatrix3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
            UniformMatrix3fv_State(location, count, transpose, value);
        }

        void UniformMatrix4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
            UniformMatrix4fv_State(location, count, transpose, value);
        }

        void ValidateProgram(GLuint program) {
            ValidateProgram_State(program);
        }
    } // namespace MG_Impl::GLImpl
} // namespace MobileGL