#pragma once

#define MOBILEGL_LOG_ACTIVE_LEVEL MOBILEGL_LOG_LEVEL_DEBUG

#define MOBILEGL_LOG_ENABLE_CONSOLE 0
#define MOBILEGL_LOG_ENABLE_FILE    1
#define MOBILEGL_LOG_ENABLE_ANDROID 1

#ifdef __ANDROID__
#define MOBILEGL_LOG_FILE_PATH "/sdcard/MG/mobilegl_log.txt"
#elif
#define MOBILEGL_LOG_FILE_PATH ""
#endif