name: Benchmark

on:
  push:
    branches: [ dev ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      BENCH_ROOT: ${{github.workspace}}/MobileGL/MG_Benchmark

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Glslang, SPIRV-Cross, SPIRV-Tools, SPIRV-Reflect, SPIRV-Headers
          vulkan-use-cache: true

      - name: Test Vulkan SDK Install
        run: |
          echo "Vulkan SDK Version=='$VULKAN_SDK_VERSION'"
          echo "VULKAN_SDK=='$VULKAN_SDK'"
          test -n "$VULKAN_SDK_VERSION" || exit 4
          ls $VULKAN_SDK/lib

      - name: Configure CMake
        working-directory: ${{env.BENCH_ROOT}}
        run: cmake -S . -B build-bench

      - name: Build
        working-directory: ${{env.BENCH_ROOT}}/build-bench
        run: cmake --build . -j${nproc}

      - name: Test
        working-directory: ${{env.BENCH_ROOT}}/build-bench
        run: ctest -V