name: Benchmark

on:
  push:
    branches: [ dev ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      # BENCH_ROOT: ${{github.workspace}}/MobileGL/MG_Benchmark
      BENCH_ROOT: ${{github.workspace}}

    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 32

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Update glslang external sources
        working-directory: ${{env.BENCH_ROOT}}/3rdparty/glslang
        run: python update_glslang_sources.py

      - name: Configure CMake
        working-directory: ${{env.BENCH_ROOT}}
        run: cmake -S . -B build-bench -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON -DBENCHMARK_ENABLE_TESTING=OFF -DBUILD_TEST=OFF -DBUILD_BENCHMARK=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build
        working-directory: ${{env.BENCH_ROOT}}/build-bench
        run: cmake --build . --parallel 4

      - name: Benchmark
        working-directory: ${{env.BENCH_ROOT}}/build-bench
        run: ctest -V -C Release