name: Build MobileGL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
        fetch-depth: 1

    - name: Cache CCache
      uses: actions/cache@main
      with:
        path: |
             ${{ github.workspace }}/ccache
        key: |
             ${{ runner.os }}-ccache-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
             ${{ runner.os }}-ccache-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Configure CMake and Build
      run: |
          git submodule update --remote --recursive
          git add .
          bash android_ci_build.bash

    - name: Upload build output
      uses: actions/upload-artifact@main
      with:
        name: MG
        path: build/*.so

