name: Test

on:
  push:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_ROOT: ${{github.workspace}}/MobileGL/MG_Test

    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 32

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Glslang, SPIRV-Cross, SPIRV-Tools, SPIRV-Reflect, SPIRV-Headers
          vulkan-use-cache: true

      - name: Test Vulkan SDK Install
        run: |
          echo "Vulkan SDK Version=='$VULKAN_SDK_VERSION'"
          echo "VULKAN_SDK=='$VULKAN_SDK'"
          test -n "$VULKAN_SDK_VERSION" || exit 4
          ls $VULKAN_SDK/lib

      - name: Configure CMake
        working-directory: ${{env.TEST_ROOT}}
        run: cmake -S . -B build-test -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        working-directory: ${{env.TEST_ROOT}}/build-test
        run: cmake --build . --parallel 4

      - name: Test
        working-directory: ${{env.TEST_ROOT}}/build-test
        run: ctest -V