name: Update Submodules
on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: 'false'
        
    - name: Update all submodules
      run: |
        ./update.bash
